work_dir: ./work_dir/NTU-RGB-D/xview/random_crop_center0.9

# feeder
feeder: co_cn.feeder.Feeder
train_feeder_args:
  data_path: ../data_small_8/NTU-RGB-D/xview/train_data.npy
  label_path: ../data_small_8/NTU-RGB-D/xview/train_label.pkl
  random_crop: True
test_feeder_args:
  data_path: ../data_small_8/NTU-RGB-D/xview/val_data.npy
  label_path: ../data_small_8/NTU-RGB-D/xview/val_label.pkl

# model
model: co_cn.net.CO_CN
model_args:
  num_class: 60
  channel: 3
  window_size: 300
  num_point: 25
  num_person: 2
  graph: co_cn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [25, 60, 80]

# training
device: [0,1,2,3]
batch_size: 4
test_batch_size: 4
num_epoch: 80
nesterov: True   ####xsub   4072 1080     ####xview    3819  1918